#!/usr/bin/env python3

# SPDX-FileCopyrightText: The RamenDR authors
# SPDX-License-Identifier: Apache-2.0

import os
import sys

from drenv import kubectl
from drenv import cache

TIMEOUT = 600


def deploy(cluster):
    print("Deploying longhorn")
    path = cache.get("longhorn", "addons/longhorn-1.7.yaml")
    kubectl.apply("--filename", path, context=cluster)


def wait(cluster):
    print("Waiting until longhorn manager is rolled out")
    kubectl.rollout(
        "status",
        "deploy/longhorn-manager",
        "--namespace=longhorn-system",
        timeout=TIMEOUT,
        context=cluster,
    )

    print("Waiting until longhorn driver is rolled out")
    kubectl.rollout(
        "status",
        "deploy/longhorn-driver-deployer",
        "--namespace=longhorn-system",
        timeout=TIMEOUT,
        context=cluster,
    )

    print("Deploying storageclass")
    path = cache.get("storageclass", "addons/longhorn-storageclass.yaml")
    kubectl.apply("--filename", path, context=cluster)


if len(sys.argv) != 2:
    print(f"Usage: {sys.argv[0]} cluster")
    sys.exit(1)

os.chdir(os.path.dirname(__file__))
cluster = sys.argv[1]

deploy(cluster)
wait(cluster)
